name: build-deploy-web

on:
    push:
        branches: [ 'main' ]

jobs:
    call-deploy-web-with-coi:
        permissions:
            contents: read
            pages: write
            id-token: write
        uses: aaronchn99/Pong/.github/workflows/deploy-web-with-coi.yml@main